// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9gIKt5UbxYn8H22Ky0vS-WGQK6I9epcY',
    appId: '1:471417235405:web:7035ca319ec3a747824684',
    messagingSenderId: '471417235405',
    projectId: 'mobile-dev-final-dc418',
    authDomain: 'mobile-dev-final-dc418.firebaseapp.com',
    storageBucket: 'mobile-dev-final-dc418.appspot.com',
    measurementId: 'G-SHRB651P21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZSuqLpH4uGORYVqfAVbiBXaIft4F_EaQ',
    appId: '1:471417235405:android:112ea1e20435b47c824684',
    messagingSenderId: '471417235405',
    projectId: 'mobile-dev-final-dc418',
    storageBucket: 'mobile-dev-final-dc418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWeZ_enLnmGke8-qe_CIAOZcaCzwahRxA',
    appId: '1:471417235405:ios:ed30bafeaa7847e7824684',
    messagingSenderId: '471417235405',
    projectId: 'mobile-dev-final-dc418',
    storageBucket: 'mobile-dev-final-dc418.appspot.com',
    iosBundleId: 'com.example.tester2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWeZ_enLnmGke8-qe_CIAOZcaCzwahRxA',
    appId: '1:471417235405:ios:563119457c53064f824684',
    messagingSenderId: '471417235405',
    projectId: 'mobile-dev-final-dc418',
    storageBucket: 'mobile-dev-final-dc418.appspot.com',
    iosBundleId: 'com.example.tester2.RunnerTests',
  );
}
